//
// Created by rjd67 on 2021/5/21.
//

#ifndef LIVEBROADCASTSERVER_PULLCONNECTION_H
#define LIVEBROADCASTSERVER_PULLCONNECTION_H

class PullConnection
{

};

#endif //LIVEBROADCASTSERVER_PULLCONNECTION_H
